### ISSUE TITLE
KSP-AVC reports new version 1.1.6.3

### ISSUE THREAD

**Issue by davedev** [linuxgurugamer/TooManyOrbits#1]
Same as the issue I reported in EVAFollower and similar to the issue I reported in SpaceTuxLibrary/ButtonManager.  

AVC reports version 1.1.6.3 is available and links to this repo, where the latest release is still 1.1.6.2.

![Annotation 2020-06-25 1941081](https://user-images.githubusercontent.com/4571729/85807100-d80f3a80-b71e-11ea-8897-d2bcb83dbefa.png)

**Comment by linuxgurugamer** [comment]
Apparently I never finished the release process.  Just did , thanks
